# Site setings
name: "Alun Xu"
description: "Musical Data Scientist"
meta_description: "illumiation and navigation"
logo:
# Author image is used in site sidebar and greetings in the home page hero text
author:
    image: "authorimage.jpg"
    greetings: "Weilcome to Aluniverse, a space to navigate, dedicate, and illuminate."
favicon: "assets/images/favicon.ico"
baseurl:
production_url: https://royce.netlify.com/
disqus: "justgoodthemes"
mailchimp_url: "//justgoodthemes.us3.list-manage.com/subscribe/post?u=78f1bab16028354caeb23aecd&amp;id=4a7330d117"
# Add your GA Tracking Id
ga_analytics:
livereload: true
# Contact form setings
email: raphael-xu@outlook.com
contact_page_description: "Horace theme comes with a contact form built-in. You can use this form with Formspree service and get up to 50 submissions for free. Also, you can easily switch to another service if you want."
thankyou_page_description: "Your message has been successfully sent. We will contact you very soon!"

# Social links
# twitter: 'justgoodthemes'
# facebook: 'username'
# github: 'justgoodthemes'
# codepen: 'username'
# dribbble: 'username'
# medium: '@username'
# instagram: 'username'
# pinterest: 'username'
# linkedin: 'username'
# producthunt: '@username'
# quora: 'username'

# Navigation
navigation:
    - text: Home
      url: /about
    - text: Research
    - text: Blog
      url: /
    - text: Search
      url: /search
    # - text: Style Guide
    #   url: /style-guide
    - text: Contact
      url: /contact

# Required Plugins
plugins_dir:
    - jekyll-paginate
    - jekyll-seo-tag
    - jekyll-sitemap

# Pagination
paginate: 5
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown

# Sass
sass:
    sass_dir: _sass
    style: compressed
